sudo: true
dist: trusty

language: php

services:
  - mongodb

php:
  - hhvm-3.12
  - hhvm-3.15

matrix:
  allow_failures:
    - php: hhvm-3.12
    - php: hhvm-3.15

env:
  global:
    - TEST_PHP_ARGS="-q -s output.txt -g XFAIL,FAIL,BORK,WARN,LEAK,SKIP -x --show-diff"
    - REPORT_EXIT_STATUS=1

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  - echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org
  - sudo apt-get install hhvm-dev hhvm-dbg

before_script:
  - "./.travis.scripts/compile.sh"

script:
  - TEST_PHP_EXECUTABLE=`which hhvm` hhvm -dhhvm.dynamic_extensions.mongodb=mongodb.so run-tests.php tests
